In [13]:
import pandas as pd
import requests
import numpy as np

# Acesso à Base de Dados
Neste notebook serão codificadas duas formas de acesso de dados, uma via requisição HTTP (busca no servidor) e a outra via arquivo direto guardado localmente na memória.

In [ ]:
# Acessando a base de dados via requisição HTTP:
headers = {'User-Agent': 'Chrome/120.0.0.0'}
response = requests.get('https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json', headers=headers)
data_frame = pd.read_json(response.text)

In [3]:
# Acessando via arquivo da base de dados armazenado localmente:
data_frame = pd.read_json('/home/felipe-rrgama/Área de trabalho/customer_highest_purchase_analisys/dataframe_archive/dados_vendas_clientes.json')

In [4]:
# Visualizando o dataframe:
data_frame.head(10)

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [5]:
# Como os dados estão aninhados, vamos normalizá-los:
data_frame = pd.json_normalize(data_frame['dados_vendas'])

In [6]:
data_frame = data_frame.explode(list(data_frame.columns[1:3]), ignore_index=True)

data_frame.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [7]:
# Verificando os tipos de dados de cada coluna da tabela:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes

In [ ]:
# A coluna Valor da compra deve ser uma coluna numérica, logo, façamos o processo de transformação do tipo str para o tipo float32
data_frame['Valor da compra'] = data_frame['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',', '.').strip())

data_frame['Valor da compra'] = data_frame['Valor da compra'].astype(np.float32)

data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float32
dtypes: float32(1), str(2)
memory usage: 532.0 bytes